### ISSUE TITLE
HTML vs JavaFX Renderer

### ISSUE THREAD

**Issue by thomaseizinger** [thomaseizinger/teletext-framework-template#2]
Zitat aus der Angabe:

> In der Übung beschränken wir uns auf einen JavaFX-Renderer.

Was machen wir jetzt ? :D
- Zaczek fragen, ob ein HTML Renderer auch ok ist?
- JavaFX Renderer implementieren
- HTML Renderer implementieren und nicht fragen

/cc @buffaloluk7 @duffleit

**Comment by buffaloluk7** [comment]
Was spricht gegen JavaFX mit WebView? Oder überhaupt gegen JavaFX?

**Comment by thomaseizinger** [comment]
Ich hab mir das eh schon angschaut, ist auch schon fast fertig :D (Hat möglicherweise noch Bugs, aber rudimentär getestet hab ichs schon :D)
War im Endeffekt eh einfacher als gedacht, siehe #3.

**Comment by thomaseizinger** [comment]
WebView wäre auch eine Idee, bringt einem aber so gut wie nix, weil das Problem eher dabei liegt, dass JavaFX nicht mit OSGi im Hinterkopf designed wurde. Bei JavaFX gehts du eigentlich immer davon aus, dass dein Programm über eine Main-Methode gestartet wird. Ich habs jetzt so gelöst, dass es ein Bundle gibt, welche eine JavaFX Applikation startet, die auf Services horcht, die `Stages` bereitstellen können und dann von der Applikation angezeigt werden.
